disabled_rules:
  - identifier_name
  - force_cast
  - line_length
  - type_body_length
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - compiler_protocol_init
  - nesting
  - function_parameter_count
excluded:
  - Carthage
  - Pods
  - Vendor
  - Shared/LocalizableStrings.swift
  - Shared/Utility/Config.swift
line_length:
  - 200
  - 300
closure_body_length:
  - 30
  - 50
identifier_name:
  min_length: 1
  max_length: 
    warning: 60
    error: 100
type_name:
  min_length: 2
  max_length: 60
file_name:
  excluded: [Images.swift, Strings.swift]
opt_in_rules:
# - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
# - conditional_returns_on_newline
  - contains_over_first_not_nil
# - convenience_type
# - discouraged_object_literal
  - discouraged_optional_boolean
# - discouraged_optional_collection
# - empty_count
  - empty_string
# - explicit_acl
# - explicit_enum_raw_value
  - explicit_init
# - explicit_self
# - explicit_type_interface
  - fallthrough
# - file_header
  - file_name
  - first_where
# - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
# - lower_acl_than_parent
# - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
# - no_extension_access_modifier
# - no_grouping_extension
# - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
# - pattern_matching_keywords
# - prefixed_toplevel_constant
  - private_outlet
  - private_action
  - private_over_fileprivate
# - prohibited_interface_builder
  - quick_discouraged_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - shorthand_operator
  - sorted_first_last
  - sorted_imports
  - static_operator
# - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
# - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
# - yoda_condition
